const events = [
  {
    event_id: "evt_001",
    source: "@liftonic_nyc",
    event_type: "fitness",
    title: "Morning strength fix...",
    description: "We're showing you this because you follow @liftonic_nyc\n\nComplete 45-minute weight training class focusing on all major muscle groups. Perfect for building strength and maintaining form.\n\nLocation: Liftonic East Village\n32 East 1st St, New York, NY",
    start_datetime: "2025-03-31T07:30:00",
    end_datetime: "2025-03-31T08:15:00",
    location_name: "@liftonic_nyc",
    neighborhood: "East Village",
    personalized_title: "Morning strength fix...",
    calendar_title: "Morning strength fix..."
  },
  {
    event_id: "evt_002",
    source: "@yogaflow_nyc",
    event_type: "fitness",
    title: "Lunchtime yoga flow",
    description: "We're showing you this because you follow @yogaflow_nyc\n\nMidday yoga class to stretch and energize. All levels welcome. Perfect for a midday reset.\n\nLocation: Yoga Flow Studio\n45 West 14th St, New York, NY",
    start_datetime: "2025-03-31T12:00:00",
    end_datetime: "2025-03-31T12:45:00",
    location_name: "@yogaflow_nyc",
    neighborhood: "Union Square",
    personalized_title: "Lunchtime yoga flow",
    calendar_title: "Lunchtime yoga flow"
  },
  {
    event_id: "evt_003",
    source: "@nyc_jazz_club",
    event_type: "music",
    title: "Jazz that doesn't disappoint...",
    description: "We're showing you this because you follow @nyc_jazz_club\n\nExperience an evening of smooth jazz with The Blue Note Quartet. Doors open at 7:30 PM.\n\nLocation: Blue Note Jazz Club\n131 W 3rd St, New York, NY",
    start_datetime: "2025-03-31T20:00:00",
    end_datetime: "2025-03-31T23:00:00",
    location_name: "@nyc_jazz_club",
    neighborhood: "Greenwich Village",
    personalized_title: "Jazz that doesn't disappoint...",
    calendar_title: "Jazz that doesn't disappoint..."
  },
  {
    event_id: "evt_004",
    source: "@foodie_nyc",
    event_type: "food",
    title: "Taco Tuesday at La Taqueria",
    description: "Authentic Mexican tacos and margaritas. Happy hour from 5-7 PM.",
    start_datetime: "2025-04-01T18:00:00",
    end_datetime: "2025-04-01T20:00:00",
    location_name: "La Taqueria",
    location_address: "78 2nd Ave, New York, NY",
    neighborhood: "East Village",
    personalized_title: "Taco Tuesday vibes...",
    calendar_title: "Taco Tuesday vibes..."
  },
  {
    event_id: "evt_005",
    source: "@art_nyc",
    event_type: "art",
    title: "Contemporary Art Exhibition Opening",
    description: "Opening night of 'Modern Perspectives' featuring emerging NYC artists. Free entry with RSVP.",
    start_datetime: "2025-04-01T19:00:00",
    end_datetime: "2025-04-01T21:00:00",
    location_name: "Gallery 456",
    location_address: "456 Broadway, New York, NY",
    neighborhood: "SoHo",
    personalized_title: "This exhibit is buzzing...",
    calendar_title: "This exhibit is buzzing..."
  },
  {
    event_id: "evt_006",
    source: "@nyc_rooftop",
    event_type: "social",
    title: "Sunset Rooftop Happy Hour",
    description: "Unwind with craft cocktails and stunning city views. Live DJ from 6-9 PM.",
    start_datetime: "2025-04-02T17:00:00",
    end_datetime: "2025-04-02T21:00:00",
    location_name: "The Rooftop at 230 Fifth",
    location_address: "230 Fifth Ave, New York, NY",
    neighborhood: "Flatiron",
    personalized_title: "Rooftop vibes with a view...",
    calendar_title: "Rooftop vibes with a view..."
  },
  {
    event_id: "evt_007",
    source: "@nyc_tech_meetup",
    event_type: "tech",
    title: "AI & Web3 Meetup",
    description: "Join fellow tech enthusiasts for networking and talks on the latest in AI and blockchain.",
    start_datetime: "2025-04-03T18:30:00",
    end_datetime: "2025-04-03T21:00:00",
    location_name: "WeWork 85 Broad",
    location_address: "85 Broad St, New York, NY",
    neighborhood: "Financial District",
    personalized_title: "Tech talk that's worth your time...",
    calendar_title: "Tech talk that's worth your time..."
  },
  {
    event_id: "evt_008",
    source: "@nyc_food_fest",
    event_type: "food",
    title: "Brooklyn Food Festival",
    description: "Sample dishes from 50+ local restaurants. Live cooking demos and food trucks.",
    start_datetime: "2025-04-04T11:00:00",
    end_datetime: "2025-04-04T19:00:00",
    location_name: "Brooklyn Bridge Park",
    location_address: "334 Furman St, Brooklyn, NY",
    neighborhood: "Brooklyn Heights",
    personalized_title: "Foodie paradise awaits...",
    calendar_title: "Foodie paradise awaits..."
  },
  {
    event_id: "evt_009",
    source: "@nyc_comedy",
    event_type: "entertainment",
    title: "Stand-up Comedy Night",
    description: "Featuring top NYC comedians. Two drink minimum, 21+.",
    start_datetime: "2025-04-05T20:00:00",
    end_datetime: "2025-04-05T22:00:00",
    location_name: "The Comedy Cellar",
    location_address: "117 MacDougal St, New York, NY",
    neighborhood: "Greenwich Village",
    personalized_title: "Laughs guaranteed...",
    calendar_title: "Laughs guaranteed..."
  },
  {
    event_id: "evt_010",
    source: "@nyc_art_gallery",
    event_type: "art",
    title: "Contemporary Photography Exhibition",
    description: "Opening reception for 'Urban Perspectives' featuring NYC street photography.",
    start_datetime: "2025-04-06T18:00:00",
    end_datetime: "2025-04-06T21:00:00",
    location_name: "Gagosian Gallery",
    location_address: "555 W 24th St, New York, NY",
    neighborhood: "Chelsea",
    personalized_title: "Art that captures the city...",
    calendar_title: "Art that captures the city..."
  },
  {
    event_id: "evt_011",
    source: "@nyc_yoga",
    event_type: "fitness",
    title: "Sunrise Yoga in Central Park",
    description: "Start your day with an energizing yoga session overlooking the park.",
    start_datetime: "2025-04-07T06:30:00",
    end_datetime: "2025-04-07T08:00:00",
    location_name: "Central Park Great Lawn",
    location_address: "Central Park, New York, NY",
    neighborhood: "Upper West Side",
    personalized_title: "Morning zen in the park...",
    calendar_title: "Morning zen in the park..."
  },
  {
    event_id: "evt_012",
    source: "@nyc_music",
    event_type: "music",
    title: "Indie Band Showcase",
    description: "Five up-and-coming indie bands performing live. Doors at 7 PM.",
    start_datetime: "2025-04-08T19:30:00",
    end_datetime: "2025-04-08T23:00:00",
    location_name: "Bowery Ballroom",
    location_address: "6 Delancey St, New York, NY",
    neighborhood: "Lower East Side",
    personalized_title: "New music discovery night...",
    calendar_title: "New music discovery night..."
  },
  {
    event_id: "evt_013",
    source: "@nyc_workshop",
    event_type: "education",
    title: "Creative Writing Workshop",
    description: "Learn storytelling techniques with award-winning author Sarah Chen.",
    start_datetime: "2025-04-09T14:00:00",
    end_datetime: "2025-04-09T16:00:00",
    location_name: "The Writers Room",
    location_address: "740 Broadway, New York, NY",
    neighborhood: "Union Square",
    personalized_title: "Unlock your writing potential...",
    calendar_title: "Unlock your writing potential..."
  },
  {
    event_id: "evt_014",
    source: "@nyc_fitness",
    event_type: "fitness",
    title: "HIIT Bootcamp",
    description: "High-intensity interval training with certified trainers. All levels welcome.",
    start_datetime: "2025-04-10T07:00:00",
    end_datetime: "2025-04-10T08:00:00",
    location_name: "Barry's Bootcamp",
    location_address: "28 W 23rd St, New York, NY",
    neighborhood: "Flatiron",
    personalized_title: "Sweat session that delivers...",
    calendar_title: "This is a new event title..."
  },
  {
    event_id: "evt_015",
    source: "@nyc_food_tour",
    event_type: "food",
    title: "Chinatown Food Tour",
    description: "Explore hidden gems and authentic cuisine in NYC's Chinatown.",
    start_datetime: "2025-04-11T11:00:00",
    end_datetime: "2025-04-11T14:00:00",
    location_name: "Chinatown",
    location_address: "Canal St & Mott St, New York, NY",
    neighborhood: "Chinatown",
    personalized_title: "Food adventure in Chinatown...",
    calendar_title: "Food adventure in Chinatown..."
  },
  {
    event_id: "evt_016",
    source: "@nyc_art",
    event_type: "art",
    title: "Museum of Modern Art Tour",
    description: "Guided tour of the latest contemporary art exhibition.",
    start_datetime: "2025-04-12T14:00:00",
    end_datetime: "2025-04-12T16:00:00",
    location_name: "MoMA",
    location_address: "11 W 53rd St, New York, NY",
    neighborhood: "Midtown",
    personalized_title: "Art that makes you think...",
    calendar_title: "Art that makes you think..."
  },
  {
    event_id: "evt_017",
    source: "@nyc_networking",
    event_type: "business",
    title: "Startup Networking Event",
    description: "Connect with founders and investors in the tech ecosystem.",
    start_datetime: "2025-04-13T18:00:00",
    end_datetime: "2025-04-13T21:00:00",
    location_name: "WeWork 85 Broad",
    location_address: "85 Broad St, New York, NY",
    neighborhood: "Financial District",
    personalized_title: "Network with the best...",
    calendar_title: "Network with the best..."
  },
  {
    event_id: "evt_018",
    source: "@nyc_theater",
    event_type: "entertainment",
    title: "Off-Broadway Play",
    description: "Award-winning play 'The City That Never Sleeps' at the Public Theater.",
    start_datetime: "2025-04-14T19:30:00",
    end_datetime: "2025-04-14T21:30:00",
    location_name: "The Public Theater",
    location_address: "425 Lafayette St, New York, NY",
    neighborhood: "East Village",
    personalized_title: "Theater that moves you...",
    calendar_title: "Theater that moves you..."
  },
  {
    event_id: "evt_019",
    source: "@nyc_meditation",
    event_type: "wellness",
    title: "Mindfulness Meditation",
    description: "Guided meditation session for stress relief and mental clarity.",
    start_datetime: "2025-04-15T12:00:00",
    end_datetime: "2025-04-15T13:00:00",
    location_name: "MNDFL Meditation",
    location_address: "123 W 18th St, New York, NY",
    neighborhood: "Flatiron",
    personalized_title: "Find your inner peace...",
    calendar_title: "Find your inner peace..."
  },
  {
    event_id: "evt_020",
    source: "@nyc_dance",
    event_type: "entertainment",
    title: "Salsa Night",
    description: "Learn salsa moves and dance the night away. Beginners welcome!",
    start_datetime: "2025-04-16T20:00:00",
    end_datetime: "2025-04-16T23:00:00",
    location_name: "Salsa Social",
    location_address: "234 W 42nd St, New York, NY",
    neighborhood: "Times Square",
    personalized_title: "Dance the night away...",
    calendar_title: "Dance the night away..."
  },
  {
    event_id: "evt_021",
    source: "@nyc_volunteer",
    event_type: "community",
    title: "Food Bank Volunteer Day",
    description: "Help pack and distribute food to those in need.",
    start_datetime: "2025-04-17T09:00:00",
    end_datetime: "2025-04-17T12:00:00",
    location_name: "City Harvest",
    location_address: "150 52nd St, Brooklyn, NY",
    neighborhood: "Sunset Park",
    personalized_title: "Make a difference today...",
    calendar_title: "Make a difference today..."
  },
  {
    event_id: "evt_022",
    source: "@nyc_photography",
    event_type: "education",
    title: "Street Photography Workshop",
    description: "Learn to capture NYC's energy through your lens.",
    start_datetime: "2025-04-18T10:00:00",
    end_datetime: "2025-04-18T13:00:00",
    location_name: "B&H Photo",
    location_address: "420 9th Ave, New York, NY",
    neighborhood: "Chelsea",
    personalized_title: "Capture the city's soul...",
    calendar_title: "Capture the city's soul..."
  },
  {
    event_id: "evt_023",
    source: "@nyc_cycling",
    event_type: "fitness",
    title: "Central Park Bike Tour",
    description: "Guided bike tour through Central Park's hidden gems.",
    start_datetime: "2025-04-19T09:00:00",
    end_datetime: "2025-04-19T11:00:00",
    location_name: "Central Park",
    location_address: "Central Park, New York, NY",
    neighborhood: "Upper West Side",
    personalized_title: "Park adventure on wheels...",
    calendar_title: "Park adventure on wheels..."
  },
  {
    event_id: "evt_024",
    source: "@nyc_cooking",
    event_type: "food",
    title: "Italian Cooking Class",
    description: "Learn to make authentic pasta from scratch with Chef Maria.",
    start_datetime: "2025-04-20T18:00:00",
    end_datetime: "2025-04-20T21:00:00",
    location_name: "Eataly",
    location_address: "200 5th Ave, New York, NY",
    neighborhood: "Flatiron",
    personalized_title: "Master the art of pasta...",
    calendar_title: "Master the art of pasta..."
  },
  {
    event_id: "evt_025",
    source: "@nyc_jazz",
    event_type: "music",
    title: "Jazz Brunch",
    description: "Sunday jazz brunch with live music and bottomless mimosas.",
    start_datetime: "2025-04-21T11:00:00",
    end_datetime: "2025-04-21T14:00:00",
    location_name: "Blue Note Jazz Club",
    location_address: "131 W 3rd St, New York, NY",
    neighborhood: "Greenwich Village",
    personalized_title: "Jazz and brunch perfection...",
    calendar_title: "Jazz and brunch perfection..."
  }
];

module.exports = events; 